### ISSUE TITLE
Failed to load the linter-glsl package

### ISSUE THREAD

**Issue by minhtrungaa** [AtomLinter/linter-glsl#46]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-glsl](https://github.com/AtomLinter/linter-glsl) package 2.0.5

### Stack Trace

Failed to load the linter-glsl package

```
At Cannot find module 'which'

Error: Cannot find module 'which'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-glsl-master/lib/linter-glsl.js:6:15)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-glsl 0.2.3 
language-glsl 2.0.1 
linter-glsl 2.0.5 
```

**Comment by andystanton** [comment]
Thanks for the report @minhtrungaa I'll take a look

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? `apm` occasionally fails to install dependencies properly.

**Comment by minhtrungaa** [comment]
i'm sorry i have try several times but still

2017-02-11 0:28 GMT+07:00 Landon Abney <notifications@github.com>:

**Comment by andystanton** [comment]
@minhtrungaa can you try removing and reinstalling with the version released today - 2.1.0?

**Comment by minhtrungaa** [comment]
i have found the problem, i works behind the proxy of my company so it's
block from accessing github. Sorry for this inconvenience

**Comment by andystanton** [comment]
Thanks for investigating @minhtrungaa!
